{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5df241a1",
   "metadata": {},
   "source": [
    "# Streamlit App for Clustering"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a669ca0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "# ===============================\n",
    "# LOAD FILES\n",
    "# ===============================\n",
    "df = pd.read_excel(\"P659_World_development_dataset.xlsx\")\n",
    "\n",
    "model = joblib.load(\"kmeans_model.joblib\")\n",
    "scaler = joblib.load(\"scaler.joblib\")\n",
    "pca = joblib.load(\"pca.joblib\")\n",
    "\n",
    "# ===============================\n",
    "# UI CONFIG\n",
    "# ===============================\n",
    "st.set_page_config(layout=\"wide\")\n",
    "\n",
    "st.title(\"🌍 Global Dev Clustering\")\n",
    "st.subheader(\"Unsupervised ML Project\")\n",
    "\n",
    "# ===============================\n",
    "# SIDEBAR\n",
    "# ===============================\n",
    "st.sidebar.header(\"Upload Dataset\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Upload Excel\", type=[\"xlsx\"])\n",
    "\n",
    "if uploaded_file:\n",
    "    df = pd.read_excel(uploaded_file)\n",
    "\n",
    "# ===============================\n",
    "# COUNTRY SELECT\n",
    "# ===============================\n",
    "country = st.selectbox(\"Select country to inspect\", df['Country'])\n",
    "\n",
    "row = df[df['Country'] == country]\n",
    "\n",
    "# ===============================\n",
    "# TRANSFORM + PREDICT\n",
    "# ===============================\n",
    "features = df.drop(columns=['Country'], errors='ignore')\n",
    "\n",
    "scaled = scaler.transform(features)\n",
    "pca_data = pca.transform(scaled)\n",
    "\n",
    "clusters = model.predict(pca_data)\n",
    "df['Cluster'] = clusters\n",
    "\n",
    "cluster_id = df[df['Country'] == country]['Cluster'].values[0]\n",
    "\n",
    "# ===============================\n",
    "# DISPLAY METRICS\n",
    "# ===============================\n",
    "st.markdown(f\"### 🌐 {country}\")\n",
    "st.write(f\"Cluster assigned: **{cluster_id}**\")\n",
    "\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "for i, col in enumerate(features.columns[:9]):\n",
    "    with [col1, col2, col3][i % 3]:\n",
    "        st.metric(col, round(row[col].values[0], 2))\n",
    "\n",
    "# ===============================\n",
    "# COMPARISON GRAPH\n",
    "# ===============================\n",
    "cluster_mean = df[df['Cluster'] == cluster_id].mean(numeric_only=True)\n",
    "\n",
    "comparison = pd.DataFrame({\n",
    "    \"Country\": row.iloc[0][features.columns],\n",
    "    \"Cluster Mean\": cluster_mean[features.columns]\n",
    "})\n",
    "\n",
    "st.subheader(\"📊 Country vs Cluster Mean\")\n",
    "st.bar_chart(comparison)\n",
    "\n",
    "# ===============================\n",
    "# CLUSTER DISTRIBUTION\n",
    "# ===============================\n",
    "st.subheader(\"Cluster Distribution\")\n",
    "st.bar_chart(df['Cluster'].value_counts())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "375f7aa6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "410f7db8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "71b9b276",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7f431e7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
